### PR TITLE
Move node-sass to peerDependencies

### PR DESCRIPTION
**Pull request by CezaryDanielNowak**
To fix support for gulp-sass@3.*

### CODE REVIEW

**Comment by CezaryDanielNowak** [comment]
@JosephClay :)

**Comment by ardeois** [comment]
@JosephClay any idea if this can be merged? Would be helpful to upgrade gulp-sass version

**Comment by JosephClay** [comment]
Sorry I haven't been active guys. I'll get this merged and published

**Comment by ardeois** [comment]
Thanks a lot !

**Comment by JosephClay** [comment]
I do not have the credentials to publish this package anymore. As a work-around, I plan on renaming the repo to re-publishing as `gulp-sass-inline-image`

**Pull request merged**
